# This is a configuration file for demonstrating OpenAirClim

# Species considered
[species]
# Species defined in emission inventories
# possible values: "CO2", "H2O", "NOx", "distance"
inv = ["CO2", "H2O", "NOx", "distance"]
# Assumed NOx species in emission inventory
# possible values: "NO", "NO2"
nox = "NO"
# Output / response species
# possible values: "CO2", "H2O", "O3", "CH4", "PMO", "cont"
out = ["CO2", "H2O", "O3", "CH4", "PMO", "cont"]

# Emission inventories                                                    
[inventories]
dir = "input/"
files = [
    "rnd_inv_2020.nc",
    "rnd_inv_2030.nc",
    "rnd_inv_2040.nc",
    "rnd_inv_2050.nc",
    #    "rnd_inv_2060.nc",
    #    "rnd_inv_2070.nc",
    #    "rnd_inv_2080.nc",
    #    "rnd_inv_2090.nc",
    #    "rnd_inv_2100.nc",
    #    "rnd_inv_2110.nc",
    #    "rnd_inv_2120.nc",
]
# base emission inventories, only considered if rel_to_base = true
rel_to_base = false
base.dir = "input/"
base.files = [
    "rnd_inv_2020.nc",
    "rnd_inv_2030.nc",
    "rnd_inv_2040.nc",
    "rnd_inv_2050.nc",
]

# Output options
[output]
# Full simulation run = true, climate metrics only = false
full_run = true
dir = "results/"
name = "example"
overwrite = true
# Computation of 2D concentration responses is not yet supported.
# possible values: false 
concentrations = false

# Time settings
[time]
dir = "../repository/"
# Time range in years: t_start, t_end, step, (t_end not included)
range = [2020, 2051, 1]
# Time evolution of emissions
# either type "scaling" or type "norm"
#file = "time_scaling_example.nc"
#file = "time_norm_example.nc"

# Global background concentrations
[background]
dir = "../repository/"
CO2.file = "co2_bg.nc"
CO2.scenario = "SSP2-4.5"
#CO2.scenario = "SSP1-1.9"
#CO2.scenario = "SSP4-6.0"
#CO2.scenario = "SSP3-7.0"
CH4.file = "ch4_bg.nc"
CH4.scenario = "SSP2-4.5"
N2O.file = "n2o_bg.nc"
N2O.scenario = "SSP2-4.5"

# Response options
[responses]
dir = "../repository/"
CO2.response_grid = "0D"
CO2.conc.method = "Sausen&Schumann"
# RF method based on Etminan et al. 2016 is used by default.
#CO2.rf.method = "Etminan_2016"

H2O.response_grid = "2D"
H2O.rf.file = "resp_RF.nc"    # AirClim response surface

O3.response_grid = "2D"
O3.rf.file = "resp_RF_O3.nc"  # tagging
#O3.rf.file = "resp_RF.nc"    # AirClim response surface, requires adjustment of CORR_RF_O3 !

CH4.response_grid = "2D"
CH4.tau.file = "resp_ch4.nc"  # tagging
CH4.rf.method = "Etminan_2016"

cont.response_grid = "cont"
cont.resp.file = "resp_cont.nc"
cont.G_comp = 0.04  # conventional: 0.04; hydrogen: 0.12 
cont.eff_fac = 1.0  # efficiency factor compared to kerosene (1.0)
cont.PMrel = 1.0  # relative PM emissions compared to kerosene (1.0)

# Temperature options
[temperature]
# valid methods: "Boucher&Reddy"
method = "Boucher&Reddy"
# Climate sensitivity parameter, Ponater et al. 2006, Table 1
# https://doi.org/10.1016/j.atmosenv.2006.06.036
CO2.lambda = 0.73
# Efficacies, Ponater et al. 2006, Table 1
H2O.efficacy = 1.14
O3.efficacy = 1.37
PMO.efficacy = 1.37
CH4.efficacy = 1.14
cont.efficacy = 0.59

# Climate metrics options
[metrics]
# iterate over elements in lists types t_0 and H
types = ["AGWP", "ATR", "AGTP"] # valid climate metrics: AGTP, AGWP, ATR
H = [31]                        # Time horizon, t_final = t_0 + H - 1
t_0 = [2020]                    # Start time for metrics calculation

# aircraft defined in inventory
[aircraft]
types = ["KER", "SAF", "LH2"]
