name: oac
channels:
  - conda-forge
dependencies:
  - joblib
  - black
  - numpy
  - pandas<3
  - jupyterlab
  - openssl
  - sphinx
  - myst-nb
  - sphinx_rtd_theme
  - sphinxcontrib-mermaid
  - sphinxcontrib-bibtex
  - sphinx-design
  - ipykernel
  - matplotlib
  - netcdf4
  - python<3.14
  - pytest-cov
  - prospector
  - pint
  - xarray
  - ca-certificates
  - pylint
  - mypy
  - pytest
  - pyroma
  - twine
  - scipy
  - deepmerge
  - ambiance
  - panel
  - pydantic
  - param
  - platformdirs
  - requests
  - pandas-stubs
  - pip
  - pip:
      # dependencies only available with pip
      - genbadge[coverage]
      - readme_renderer[md]
      - joblib-stubs
