name: oac_minimal
channels:
  - conda-forge
dependencies:
  - joblib
  - numpy
  - pandas<3
  - matplotlib
  - python
  - pint
  - xarray
  - netcdf4
  - scipy
  - deepmerge
  - ambiance
  - pydantic
