name: oac_minimal
channels:
- conda-forge
- nodefaults
dependencies:
- python 3.13.*
- netcdf4 *
- joblib *
- numpy *
- pandas <3
- matplotlib-base *
- pint *
- xarray *
- scipy *
- deepmerge *
- ambiance *
- pydantic *
- platformdirs *
- requests *
