name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11.5"]
    steps:
    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: false
        python-version: ${{ matrix.python-version }}
        miniforge-version: latest
    - name: Conda info
      run: |
        conda info
        conda list
    - name: Set PYTHONPATH variable
      run: |
        echo $PYTHONPATH