name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: false
        python-version: ["3.11.5"]
        miniforge-version: latest
    - name: Conda info
      run: |
        conda info
        conda list
    - name: Set PYTHONPATH variable
      run: |
        echo $PYTHONPATH